{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "adapt.fullname" . }}-env
  labels:
    {{- include "adapt.labels" . | nindent 4 }}
stringData:
  {{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
{{- end }}
